version: "3.6"
networks:
  services_besu1:
    external: true
services:
  ethsigner1:
    image: consensys/ethsigner
    command:
      [
        "--chain-id=44844",
        "--http-listen-host=0.0.0.0",
        "--http-listen-port=18545",
        "--downstream-http-port=8545",
        "--downstream-http-host=services-besu1-1",
        "multikey-signer",
        "--directory=/opt/ethsigner/keys",
      ]
    volumes:
      - ./config/ethsigner1:/opt/ethsigner/keys
    ports:
      - 18545:18545/tcp
    networks:
      - services_besu1
