version: "3.6"
networks:
  services_besu2:
    external: true
services:
  ethsigner2:
    image: consensys/ethsigner
    command:
      [
        "--chain-id=55755",
        "--http-listen-host=0.0.0.0",
        "--http-listen-port=18545",
        "--downstream-http-port=8545",
        "--downstream-http-host=services-besu2-1",
        "multikey-signer",
        "--directory=/opt/ethsigner/keys",
      ]
    volumes:
      - ./config/ethsigner2:/opt/ethsigner/keys
    ports:
      - 17545:18545/tcp
    networks:
      - services_besu2
